name: latexsongparser
description: A Parser for LatexSongs
version: 1.0.0
repository: https://github.com/Webstonesl/DartLatexSongsParser

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  antlr4: ^4.13.1
  quiver: ^3.2.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
